/* ============================================================
   INSTITUTIONAL REPORTS & DATA VIEWS (Setup 4 §20, §24).
   Report builder (tables only, aggregated, privacy-safe) plus
   registry views: village books, geographic coverage, schools,
   archival collections & finding aids.
   ============================================================ */
(function () {
  'use strict';

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {
      return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c];
    });
  }
  var Store = window.RootsInstStore;

  function groupCount(people, getter) {
    var out = {};
    people.forEach(function (p) {
      var k = getter(p) || 'Unspecified';
      out[k] = (out[k] || 0) + 1;
    });
    return out;
  }
  function tableHtml(headers, rows) {
    return '<div class="ws-table-wrap"><table class="ws-table"><thead><tr>' +
      headers.map(function (h) { return '<th>' + esc(h) + '</th>'; }).join('') + '</tr></thead><tbody>' +
      rows.map(function (r) {
        return '<tr>' + r.map(function (c) { return '<td>' + esc(c) + '</td>'; }).join('') + '</tr>';
      }).join('') + '</tbody></table></div>';
  }

  /* ---------------- report builder ---------------- */
  window.RootsInstViews.push({
    id: 'reports',
    label: 'Reports',
    icon: '📊',
    perm: 'inst.reports.run',
    render: function (host, ctx) {
      var access = ctx.access;
      var people = (window.PEOPLE || []).filter(access.inGeography);

      var html = '<div class="ws-page-head"><div><h2>Report Builder</h2>' +
        '<p class="sub">Aggregated tables only — no person-level rows leave the workspace</p></div></div>' +
        '<div class="ws-filters">' +
        '<select id="rpGroup"><option value="province">Group: Province</option><option value="district">Group: District</option>' +
        '<option value="totem">Group: Totem</option><option value="language">Group: Language</option>' +
        '<option value="gender">Group: Gender</option><option value="status">Group: Status</option>' +
        '<option value="villageBook">Group: Village book</option><option value="chief">Group: Chiefdom</option></select>' +
        '<select id="rpFilterField"><option value="">No filter</option><option value="province">Province is</option><option value="totem">Totem is</option>' +
        '<option value="status">Status is</option><option value="gender">Gender is</option></select>' +
        '<input id="rpFilterValue" placeholder="Value" style="max-width:160px;">' +
        '<button class="ws-btn" id="rpRun">RUN REPORT</button>' +
        '<button class="ws-btn ghost" id="rpCsv" disabled>⬇ CSV</button></div>' +
        '<div id="rpOut">' +
        '<div class="ws-panel"><h4>Recommended reports</h4>' +
        (ctx.typeCfg.recommendedReports || []).map(function (r) {
          return '<div class="ws-row static">📈 ' + esc(r) + '</div>';
        }).join('') + '</div></div>';

      host.innerHTML = html;
      var lastTable = null;

      function getters() {
        return {
          province: function (p) { return (p.admin || {}).province; },
          district: function (p) { return (p.admin || {}).district; },
          totem: function (p) { return (p.kinship || {}).mutupo; },
          language: function (p) { return (p.ethnicity || {}).languageCluster || (p.ethnicity || {}).specificGroup; },
          gender: function (p) { return p.gender === 'm' ? 'Male' : p.gender === 'f' ? 'Female' : String(p.gender || '').toUpperCase(); },
          status: function (p) { return p.died ? 'Deceased' : 'Living'; },
          villageBook: function (p) { return (p.admin || {}).villageBookId; },
          chief: function (p) { return (p.admin || {}).chief; }
        };
      }

      document.getElementById('rpRun').addEventListener('click', function () {
        var gk = document.getElementById('rpGroup').value;
        var ff = document.getElementById('rpFilterField').value;
        var fv = document.getElementById('rpFilterValue').value.trim().toLowerCase();
        var subset = people.filter(function (p) {
          if (!ff || !fv) return true;
          var val = getters()[ff](p);
          return String(val || '').toLowerCase() === fv ||
            String(val || '').toLowerCase().indexOf(fv) !== -1;
        });
        var counts = groupCount(subset, getters()[gk]);
        var keys = Object.keys(counts).sort();
        lastTable = {
          headers: [gk.toUpperCase(), 'RECORDS'],
          rows: keys.map(function (k2) { return [k2, counts[k2]]; })
        };
        document.getElementById('rpOut').innerHTML =
          tableHtml(lastTable.headers, lastTable.rows) +
          '<div class="hint" style="margin-top:8px;">Aggregated from ' + subset.length +
          ' record(s) · Privacy level: AGGREGATED · Generated by ' + esc(ctx.session.adminName) + '</div>';
        document.getElementById('rpCsv').disabled = false;
        Store.logOrgAudit('RUN_REPORT', 'Report', gk, {});
      });

      document.getElementById('rpCsv').addEventListener('click', function () {
        if (!lastTable) return;
        ctx.csv('roots-report-' + Date.now() + '.csv', lastTable.headers, lastTable.rows);
        ctx.toast('Report CSV downloaded.');
      });
    }
  });

  /* ---------------- village books registry ---------------- */
  window.RootsInstViews.push({
    id: 'villages',
    label: 'Village Books',
    icon: '📗',
    perm: 'inst.villages',
    render: function (host, ctx) {
      var access = ctx.access;
      var books = {};
      (window.PEOPLE || []).filter(access.inGeography).forEach(function (p) {
        var a = p.admin || {};
        var key = a.villageBookId || a.sabhuku;
        if (!key) return;
        var b = books[key] = books[key] || { sabhuku: a.sabhuku || '—', chief: a.chief || '—', district: a.district || '—', province: a.province || '—', n: 0 };
        b.n++;
      });
      var keys = Object.keys(books).sort();
      host.innerHTML = '<div class="ws-page-head"><div><h2>Village Books Registry</h2>' +
        '<p class="sub">' + keys.length + ' village book(s) in scope</p></div></div>' +
        (keys.length ? tableHtml(
          ['VILLAGE BOOK / SABHUKU', 'CHIEFDOM', 'DISTRICT', 'PROVINCE', 'PEOPLE'],
          keys.map(function (k) {
            var b = books[k];
            return [String(k), b.chief, b.district, b.province, b.n];
          })) : '<div class="ws-empty">No administrative geography in the approved scope.</div>');
    }
  });

  /* ---------------- places / coverage ---------------- */
  window.RootsInstViews.push({
    id: 'places',
    label: 'Places',
    icon: '📍',
    perm: 'inst.overview',
    render: function (host, ctx) {
      var access = ctx.access;
      var people = (window.PEOPLE || []).filter(access.inGeography);
      var provs = groupCount(people, function (p) { return (p.admin || {}).province || p.location; });
      var dists = groupCount(people, function (p) { return (p.admin || {}).district; });
      var wards = groupCount(people, function (p) { return (p.admin || {}).ward; });
      host.innerHTML = '<div class="ws-page-head"><div><h2>Geographic Coverage</h2>' +
        '<p class="sub">Where approved data exists · Scope: ' + esc(access.scopeLabel) + '</p></div></div>' +
        '<div class="ws-two-col"><div class="ws-panel"><h4>Provinces (' + Object.keys(provs).length + ')</h4>' +
        tableHtml(['PROVINCE', 'RECORDS'], Object.keys(provs).sort().map(function (k) { return [k, provs[k]]; })) +
        '</div><div class="ws-panel"><h4>Districts (' + Object.keys(dists).length + ') · Wards (' + Object.keys(wards).length + ')</h4>' +
        tableHtml(['DISTRICT', 'RECORDS'], Object.keys(dists).sort().map(function (k) { return [k, dists[k]]; })) +
        '</div></div>';
    }
  });

  /* ---------------- schools registry (EDUCATION) ---------------- */
  window.RootsInstViews.push({
    id: 'schools',
    label: 'Schools',
    icon: '🏫',
    perm: 'inst.overview',
    render: function (host, ctx) {
      var schools = window.SCHOOLS_ZW || [];
      host.innerHTML = '<div class="ws-page-head"><div><h2>School Registry</h2>' +
        '<p class="sub">' + schools.length + ' schools · reference data for education programmes</p></div></div>' +
        '<div class="ws-filters"><input id="scQ" placeholder="Search school name">' +
        '<button class="ws-btn" id="scGo">SEARCH</button></div><div id="scOut"></div>';
      function draw(q) {
        q = (q || '').toLowerCase();
        var list = schools.filter(function (s) { return !q || s.toLowerCase().indexOf(q) !== -1; }).slice(0, 80);
        document.getElementById('scOut').innerHTML =
          '<div class="ws-count">' + list.length + ' shown</div>' + tableHtml(['SCHOOL'], list.map(function (s) { return [s]; }));
      }
      document.getElementById('scGo').addEventListener('click', function () { draw(document.getElementById('scQ').value); });
      draw('');
    }
  });

  /* ---------------- collections (ARCHIVE / HERITAGE) ---------------- */
  window.RootsInstViews.push({
    id: 'collections',
    label: 'Collections',
    icon: '🏛️',
    perm: 'inst.collections',
    module: 'ARCHIVE_SUITE',
    moduleTitle: 'Archival Collections',
    altModule: 'HERITAGE_SUITE',
    render: function (host, ctx) {
      var access = ctx.access;
      if (!access.hasModule('ARCHIVE_SUITE') && !access.hasModule('HERITAGE_SUITE')) {
        host.innerHTML = ctx.lockCard('plan', 'Collections');
        return;
      }
      var people = (window.PEOPLE || []).filter(access.inGeography);
      var fonds = {};
      people.forEach(function (p) {
        var f = p.sourceName || 'Unattributed accessions';
        fonds[f] = fonds[f] || { items: 0, notes: 0 };
        fonds[f].items++;
        if (p.sourceNote) fonds[f].notes++;
      });
      var keys = Object.keys(fonds).sort();
      host.innerHTML = '<div class="ws-page-head"><div><h2>Collections</h2>' +
        '<p class="sub">' + keys.length + ' fonds/collections · ' + people.length + ' catalogued items</p></div></div>' +
        (keys.length ? tableHtml(['COLLECTION / FOND', 'ITEMS', 'ITEMS WITH SOURCE NOTES'],
          keys.map(function (k) { return [k, fonds[k].items, fonds[k].notes]; }))
          : '<div class="ws-empty">No collection metadata in scope.</div>');
    }
  });

  /* ---------------- finding aids (ARCHIVE) ---------------- */
  window.RootsInstViews.push({
    id: 'findingAids',
    label: 'Finding Aids',
    icon: '🧾',
    perm: 'inst.collections',
    module: 'ARCHIVE_SUITE',
    moduleTitle: 'Finding Aids & EAD3',
    render: function (host, ctx) {
      var access = ctx.access;
      var people = (window.PEOPLE || []).filter(access.inGeography).filter(function (p) { return p.sourceName; });
      host.innerHTML = '<div class="ws-page-head"><div><h2>Finding Aids</h2>' +
        '<p class="sub">Source notes feed EAD3 export components</p></div></div>' +
        '<div class="ws-panel"><h4>EAD3 readiness</h4><div class="kv">' +
        '<div><span>Fonds with notes</span><b>' + people.filter(function (p) { return p.sourceNote; }).map(function (p) { return p.sourceName; }).filter(function (v, i, a) { return a.indexOf(v) === i; }).length + '</b></div>' +
        '<div><span>EAD3 export available</span><b>' + (access.allowedExports.indexOf('EAD3') !== -1 ? 'Yes — see Exports' : 'Requires Archive Suite') + '</b></div>' +
        '<div><span>EAC-CPF authority records</span><b>Planned — Data Governance Framework phase 2</b></div>' +
        '</div></div>' +
        tableHtml(['SOURCE', 'NOTE'],
          people.slice(0, 40).map(function (p) { return [p.sourceName, p.sourceNote || '—']; }));
    }
  });
})();
